export default {
  request: {
    requestNo: "request_id",
    requestorName: "requestor_name",
    nbkId: "nbk_id",
    phoneNo: "phone_no",
    location: "requestor_location",
    requestorEmail: "email_id",
    addlRecipients: "addl_recipients",
    hierarchyCode: "hierarchy_code",
    requestedDueDate: "requested_due_data",
    dealCode: "deal_code",
    clientName: "client_name",
    requestType: "request_type",
    sectorDesk: "sector_desk",
    requestInstructions: "requested_instructions",
    attachedFiles: "attached_files",
    requestStatus: "request_status",
    researcherName: "researcher_name",
    submittedDate: "submited_date",
    actualDueDate: "actual_due_date",
    completedDate: "completed_date",
    parentReq: "parent_req",
    workCategory: "work_category",
    tatCategory: "tat_category",
    addlComments: "addl_comments",
  },
};
